config/routes.rb
Rails.application.routes.draw do
 root 'home_pages#index'
 resources :topics, only: [:index, :show]
 get 'practice_colors', to: 'home_pages#practice_colors'
 get 'learn_colors', to: 'home_pages#learn_colors'
 get 'colors', to: 'home_pages#colors'
 get 'numbers', to: 'home_pages#numbers'
 get 'practice_numbers', to: 'home_pages#practice_numbers'
 get 'learn_numbers', to: 'home_pages#learn_numbers'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController

  def index
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
  end

  def colors
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/home_pages/colors.html.erb
<html>
<body class="color-body">

<%= image_tag 'color-palette1.jpg', class: 'hero_image2' %>

<br><br><br>
<h1>Learn Your <b>Colors</b> With Us!</h1>

<br />
<div class="col-xs-10 col-xs-offset-1 features text-center">
  <div class="booyah-box2 col-sm-5 ">
  <a href="practice_colors"><span></span></a>
  <h1 align="center" >Learn</h1>
    <br /> 
  <h4>Check out all the colors at once! Click on each color to hear what color it is and see how it is spelled.</h4>
  </div>

  <div class="booyah-box3 col-sm-5 col-sm-offset-2">
    <a href="practice_colors"><span></span></a>
    <h1 align="center">Practice</h1>
    <br />
    <h4>Try to guess each color! Don't worry if you aren't sure, just click on the color to hear what it is!</h4>
  </div>
  <br class="clr" />

</div>


</body>
</html>


app/views/home_pages/index.html.erb

<body>

<%= image_tag 'learning4.jpg', class: 'hero_image1' %>

<div class="col-xs-10 col-xs-offset-1 features text-center">
  <div class="booyah-box1 col-sm-5 ">
  <a href="colors"><span></span></a>
  <br>
  <h1 align="center">Colors</h1>
  <br>
  </div>

  <div class="booyah-box4 col-sm-5 col-sm-offset-2">
    <a href="numbers"><span></span></a>
    <br>
    <h1 align="center">Numbers</h1>
    <br>
  </div>

  <br class="clr" />

</div>

<br class="clr" />

</body>

app/views/home_pages/numbers.html.erb
<html>
<body class="number-body">

<%= image_tag 'numbershero.jpg', class: 'hero_image2' %>

<h1>Learn Your <b>Numbers</b> With Us!</h1>

<br />
<div class="col-xs-10 col-xs-offset-1 features text-center">
  <div class="booyah-box5 col-sm-5 ">
  <a href="practice_numbers"><span></span></a>
  <h1 align="center" >Learn</h1>
    <br /> 
  <h4>Check out all the numbers at once! Click on each number to hear what it is and see how it is spelled.</h4>
  </div>

  <div class="booyah-box6 col-sm-5 col-sm-offset-2">
    <a href="practice_numbers"><span></span></a>
    <h1 align="center">Practice</h1>
    <br />
    <h4>Try to guess each number! Don't worry if you aren't sure, just click on the number to hear what it is!</h4>
  </div>
  <br class="clr" />

</div>


</body>
</html>

app/views/home_pages/practice_colors.html.erb
<html>
<body>

<%= audio_tag 'red.mp3', id: 'red', data_key: 'red' %>
<%= audio_tag 'green.mp3', id: 'green', data_key: 'green' %>
<%= audio_tag 'black.mp3', id: 'black', data_key: 'black' %>
<%= audio_tag 'brown.mp3', id: 'brown', data_key: 'brown' %>
<%= audio_tag 'pink.mp3', id: 'pink', data_key: 'pink' %>
<%= audio_tag 'orange.mp3', id: 'orange', data_key: 'orange' %>
<%= audio_tag 'purple.mp3', id: 'purple', data_key: 'purple' %>
<%= audio_tag 'white.mp3', id: 'white', data_key: 'white' %>
<%= audio_tag 'yellow.mp3', id: 'yellow', data_key: 'yellow' %>
<%= audio_tag 'blue.mp3', id: 'blue', data_key: 'blue' %>

<div class="container" id='colors'>
  <h1>What color is the circle?</h1>
  <div class="circle" id="element1"><h1 class="hid name"></h1></div>
  <!-- <h1 class="hid name"></h1> -->
  <div class="btn btn-primary color-btn" style="border-radius:40px;" id="nextColor"><span class="color-btn-txt">Change Color</span></div>
  <br><br>
  <h2>(Click the circle to find out)</h2>
  <br class="clr" />
</div>





<script>
  function getRand(){
    return Math.floor(Math.random() *
      colorList.length);
  }

  var colorList = [
    {
      color: "black",
      hex: "black",
    },
    {
      color: "blue",
      hex: "blue",
    },
    {
      color: "brown",
      hex: "#613107"
    },
    {
      color: "green",
      hex: "green",
    },
    {
      color: "orange",
      hex: "orange",
    },
    {
      color: "pink",
      hex: "pink",
    },
    {
      color: "purple",
      hex: "purple",
    },
    {
      color: "red",
      hex: "red",
    },
    {
      color: "white",
      hex: "white",
    },
    {
      color: "yellow",
      hex: "yellow"
    }
  ];

  var orig = getRand();
  $("#element1").css("background", colorList[orig].hex);

  var audioElement = document.createElement('audio');

  $('.circle').click(function() {
    $(this).parent().find('.name').css('visibility', 'visible');
    $(this).parent().find('.name').html(colorList[orig].color);
    document.getElementById(colorList[orig].color).play();
  });

  $('#nextColor').click(function(){
    var num = getRand();
    orig = num;
    $("#element1").css("background", colorList[orig].hex);
    $(this).parent().find('.name').css('visibility', 'hidden');
  }); 

</script>

</body>
</html>

app/views/home_pages/practice_numbers.html.erb
<html>
<body>

<%= audio_tag 'one.mp3', id: 'one'%>
<%= audio_tag 'two.mp3', id: 'two'%>
<%= audio_tag 'three.mp3', id: 'three'%>
<%= audio_tag 'four.mp3', id: 'four'%>
<%= audio_tag 'five.mp3', id: 'five'%>
<%= audio_tag 'six.mp3', id: 'six'%>
<%= audio_tag 'seven.mp3', id: 'seven'%>
<%= audio_tag 'eight.mp3', id: 'eight'%>
<%= audio_tag 'nine.mp3', id: 'nine'%>
<%= audio_tag 'ten.mp3', id: 'ten'%>
<%= audio_tag 'zero.mp3', id: 'zero'%>

<div class="container" id='number'>
  <h1>What number is this?</h1>
  <div id="num_img"><%= image_tag 'one.gif', class: "num_img_class" %></div>
  <h2 class="number-name">one</h2>
  <div class="btn btn-primary number-btn" style="border-radius:40px;" id="nextNumber"><span class="number-btn-txt">Change Number</span></div>
  <br><br>
  <h2>(Click the number to find out)</h2>
  <br class="clr" />
</div>





<script>
  function getRand(){
    return Math.floor(Math.random() *
      numberList.length);
  }

  var numberList = [
    {
      number: "one",
      url: "/assets/one.gif"
    },
    {
      number: "two",
      url: "/assets/two.gif"
    },
    {
      number: "three",
      url: "/assets/three.gif"
    },
    {
      number: "four",
      url: "/assets/four.gif"
    },
    {
      number: "five",
      url: "/assets/five.gif"
    },
    {
      number: "six",
      url: "/assets/six.gif"
    },
    {
      number: "seven",
      url: "/assets/seven.gif"
    },
    {
      number: "eight",
      url: "/assets/eight.gif"
    },
    {
      number: "nine",
      url: "/assets/nine.gif"
    }
  ];

  // var orig = getRand();
  // $(".num_img_class").attr('src', numberList[orig].url);

  var orig = 0;

  var audioElement = document.createElement('audio');

  $('#num_img').click(function() {
    $(this).parent().find('.number-name').css('visibility', 'visible');
    $(this).parent().find('.number-name').html(numberList[orig].number);
    document.getElementById(numberList[orig].number).play();
  });

  $('#nextNumber').click(function(){
    var num = getRand();
    orig = num;   
    $(this).parent().find('.number-name').css('visibility', 'hidden'); 
    $(".num_img_class").attr('src', numberList[orig].url);    
  }); 

</script>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Learningwithus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div id="wrap">
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Learning With Us', root_path, class: 'navbar-brand' %>
        <!-- <a class="navbar-brand" href="">Learning With Us</a> -->
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <!--       <ul class="nav navbar-nav">
          <li><a href="#">Link</a></li>
        </ul> -->
        <ul class="nav navbar-nav navbar-right">
          <!-- <li><a href="#">Link</a></li> -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Topics<b class="caret"></b></a>
            <ul class="dropdown-menu">
    <!--           <li>
                <%= link_to 'All Topics', topics_path %>
              </li> -->
              <!-- <li class="divider"></li> -->
              <li>
              <%= link_to 'Colors', colors_path %>
              </li>
              <li>
              <%= link_to 'Numbers', numbers_path %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>


  <%= yield %>

  </div>

<br class="clr" />



  <div class="container" id="footer">  
      <div class="col-xs-12 col-sm-6 foot-space text-center">
        <b>Created by Christopher Ross</b>
        <br />
        <%= link_to 'http://www.crossphd.com', :target => "_blank" do %>
          <%= image_tag 'crossphd.jpg', class: 'social-button' %>
        <% end %>
        <%= mail_to "chris@crossphd.com" do %>
          <span>chris@crossphd.com</span>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-6 foot-space text-center social">
        <b>Social</b>
        <br>
        <%= link_to 'https://twitter.com/crossphd', :target => "_blank" do %>
          <%= image_tag 'twitter2.png', class: 'social-button' %>
        <% end %>
        <%= link_to 'https://github.com/CRossPhD', :target => "_blank" do %>
          <%= image_tag 'github2.png', class: 'social-button' %>
        <% end %>
        <%= link_to 'https://medium.com/@crossphd', :target => "_blank" do %>
          <%= image_tag 'medium2.png', class: 'social-button' %>
        <% end %>
      </div>
  </div>


</body>
</html>

app/views/topics/index.html.erb
<br />

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center">Learn something today</h1>
  <hr />

  <% topics.each do |topic| %>
    <h2 class'"text-center"><%= topic.title %></h2>
    <br>
    <div class="col-sm-8 col-xs-12">
      <%= topic.description %>
    </div>
    <div class="col-sm-4 col-xs-12 text-center">
      <%= link_to 'Button', '#', class: 'btn btn-primary btn-large' %>
    </div>
    <br class="clr" />
  <% end %>
</div>